name: Build Package
on: [workflow_dispatch]
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm install
    - name: build package
      run: npm run buildDebian && npm run buildRedhat && npm run buildLinuxArm64 && npm run buildRaspi
    - name: upload package
      uses: actions/upload-artifact@v2
      with:
        name: linux-package
        path: |
          dist/app/*.deb
          dist/app/*.rpm
